services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: podcast
      POSTGRES_PASSWORD: podcast
      POSTGRES_DB: podcast-agent
      PGDATA: /var/lib/postgresql/podcast-data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U podcast -d podcast-agent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - podcast_postgres:/var/lib/postgresql/podcast-data:rw
    ports:
      - "5434:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
  
  elasticsearch:
    image: elasticsearch:9.1.1  
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    volumes:
      - podcast_es9:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 4g

  kibana:
    image: kibana:9.1.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:10.4.7
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_DEFAULT_THEME: dark
    volumes:
      - podcast_grafana:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
volumes:
  podcast_postgres:
    name: spotify-project_podcast_postgres
  podcast_es9:
    name: spotify-project_podcast_es9
  podcast_grafana:
    name: spotify-project_podcast_grafana
